# -*- coding: utf-8 -*-
"""Rename_Resize

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HSPbjfkJNDHmBLdWRtiBtyr4yFjLhrSE
"""

labels=["a_minor","a_major",
        "b_major","b_minor",
        "c_major","c_minor",
        "d_major","d_minor",
        "e_major","e_minor",
        "f_major","f_minor",
        "g_major","g_minor"]

import os

import cv2
import PIL
from PIL import Image
import numpy as np
import cv2
path=" "

def rename(path,labels):
  chords=[]
  for label in labels:
    folders=os.path.join(path, label)
    print(folders)
    i=0
    for image in os.listdir(folders):
      dest =os.path.join(folders, (str(label)+"_"+str(i) + ".jpg"))
      image_source=os.path.join(folders, image)
      print(dest)
      os.rename(image_source, dest)
      i+=1

def resize(path,labels):
  chords=[]
  for label in labels:
    folders=os.path.join(path, label)
    print(folders)
    for image in os.listdir(folders):
      print(os.path.join(folders, image))
      img_array = Image.open(os.path.join(folders, image))
      img_array_flip = img_array.transpose(Image.FLIP_LEFT_RIGHT)
      resizedImage = img_array_flip.resize((640, 640))
      resizedImage.save(os.path.join(folders, image))